#! /usr/local/bin/bash

(
  cd ~/Projects/cuny_curriculum/query_downloads

  # Get any new course catalog query results
  export LFTP_PASSWORD=`cat /Users/vickery/.lftpwd`
  if [[ `hostname` =~ cuny.edu  ]]
  then /usr/local/bin/lftp -f ../getcunyrc
  else echo "Skip Tumbleweed access from `hostname`"
  fi

  # Strip non-UTF-8 chars from query results
  let num_converted=0

  for file in *.csv
  do
    if [[ -e $file ]]
    then
      echo -n "Converting $file ..."
      iconv -c -t utf-8 $file > ../queries/$file
      rm $file 
      echo ' done.'
      let num_converted=num_converted+1
    else
      echo 'No files to convert'
    fi
  done
  if [[ num_converted -eq 0 ]]
  then exit 1
  else exit 0
  fi
)
