#! /usr/local/bin/bash

# Wait until one or more files with names matching pattern (default, CV) shows up in tumbleweed.
#
# Used when a query has to be rescheduled manually before re-running update_db because of an earlier
# failure.
#
# Use -p to ask for a pop-up at the end.
# Use -m to ask for email at the end.

pattern=CV
pop_up='no'
email='no'

while [[ $# > 0 ]]
do
  case $1 in
    -p) pop_up='yes' ;;
    -m) email='yes' ;;
     *) pattern=$1 ;;
  esac
  shift
done
echo looking for $pattern
let minutes=0
suffix=''
while [[ `lftp -f ~/.tumblerc |ack $pattern > /dev/null; echo $?` != '0' ]]
do sleep 60
   let $(( minutes += 1 ))
   echo looking for $pattern for $minutes minute$suffix
   suffix='s'
done
echo ready
if [[ $pop_up == 'yes' ]]
then
  osascript -e 'display alert "$pattern has arrived"' > /dev/null
fi
if [[ $email == 'yes' ]]
then sendemail -s "$pattern has arrived" cvickery@qc.cuny.edu <<EOD
Rejoice.
EOD
fi
